### PR TITLE
Major upgrade for libraries

### LINKED ISSUE #56: Major upgrade for libraries
Many outdated, security vulnerabilities, etc.

### PR DESCRIPTION
**Pull request by Saeger**
Fixes #56

Breaking changes:

- From Joi 14 to Joi 17 (Many Schema changes. Please check JOI's webpage: https://joi.dev/resources/changelog/ )

### CODE REVIEW

**Review by dr-alexalves — APPROVED** [review]
I think we also need to check the interfaces that we expose. Would be better if we could keep the way we already use. But, if needed, we change it here and where we use.

**Comment by dr-alexalves** [comment]
As I don't have write access, my approval and nothing is the same. :)

**Comment by Saeger** [comment]
> I think we also need to check the interfaces that we expose. Would be better if we could keep the way we already use. But, if needed, we change it here and where we use.

I will test in deployment-service with yalc

**Comment by dr-alexalves** [comment]
> > I think we also need to check the interfaces that we expose. Would be better if we could keep the way we already use. But, if needed, we change it here and where we use.
> 
> I will test in deployment-service with yalc

Perfect!

**Comment by juliuscc** [comment]
LGTM 👍

**Pull request merged**
