### PR TITLE
docs: update reame and examples documentation

### PR DESCRIPTION
**Pull request by Timberbain**
The latest version of bagger has changed its exports. This update to the documentation matches this change.

### CODE REVIEW

**Comment by juliuscc** [comment]
This looks great. I still think that some of the examples do not work. Especially the first one in the readme.

**Comment by juliuscc** [comment]
I don't think this is how it works anymore.

```javascript
bagger
  .addRequest()
  .method('get')
  .path('/bags')
  .tag('bags')
  .tag('build')
```

**Comment by juliuscc** [comment]
This looks great! Is it out of scope to add documentation for `bagger.addComponent()` and `.addSecurity(scheme, scopes)` in API Reference?

**Comment by Timberbain** [comment]
Maybe we could have that as a separate issue. That is more like extending the documentation.

**Pull request merged**
